#pragma once

#include "excgrid/kernel.hpp"

namespace excgrid {

/// \defgroup excgrid-kernels The shipped kernel functions
///
/// Every LDA/GGA functional below is generated by the Yacas codegen
/// pipeline (xc_defs/*.ey -> generated/*.cpp, committed; see
/// tools/regenerate.py and the maintainer guide).  The generated
/// definitions live in excgrid/generated/ and are ordinary library
/// sources - this header is the hand-written declaration surface, kept
/// in sync by the add-a-functional procedure (docs/maintainer-guide.md).
///
/// Two tiers come out of one `.ey`: the order-1 kernel - the energy density
/// and the first derivatives, which Vxc assembly consumes - and the
/// functional's SECOND-DERIVATIVE tier, a function filling the contract's
/// materialised matrix from the same expression.  Both are declared here, in
/// registry order, under one name per functional: the tier of `Foo` is
/// `FooSecondDerivatives`.
/// \{

/// Slater (Dirac) LDA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue SlaterExchange(double rhoA, double rhoB);

/// VWN5 LDA correlation (the interpolation-V parametrization).
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Vwn5Correlation(double rhoA, double rhoB);

/// VWN3 LDA correlation (the RPA-parameter parametrization) - distinct
/// from VWN5, never conflated.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Vwn3Correlation(double rhoA, double rhoB);

/// PW92 LDA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Pw92Correlation(double rhoA, double rhoB);

/// Becke 1988 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Becke88Exchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Wang 1991 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Pw91Exchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Burke-Ernzerhof 1996 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue PbeExchange(double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// revPBE GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue RevPbeExchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// RPBE (Hammer-Hansen-Norskov 1999) GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue RpbeExchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// mPW91 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue MPw91Exchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// PBEsol GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue PbeSolExchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Lee-Yang-Parr 1988 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue LypCorrelation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Burke-Ernzerhof 1996 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue PbeCorrelation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Wang 1991 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Pw91Correlation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew 1986 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue P86Correlation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// \name The second-derivative tiers
///
/// One per functional whose source can afford the symbolic second
/// differentiation, emitted from the same expression as the kernel above it and
/// filling the contract's upper triangle over the components that kernel reads,
/// in identifier order.  A functional without one has no declaration here and
/// refuses a tier request by capability; see XcFunctional::SecondDerivativeMask.
/// The matrix is left untouched at a point the kernel's own guards do not
/// answer.  The tau tier's is the one tier not declared here, because its
/// kernel is wider than the two kernel-pointer types these functions return; it
/// is named where the registry builds it.
///
/// These are the generated entry points.  A consumer goes through
/// XcFunctional::EvaluatePointMaterialising, which re-packs this matrix onto
/// the caller's own mask; the functions below are the generated layer under it
/// and their packing is the kernel's argument order, not the caller's.
/// \{
/// \ingroup excgrid-kernels

/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param matrix Filled with the upper triangle over (rhoA, rhoB).
/// \ingroup excgrid-kernels
void SlaterExchangeSecondDerivatives(double rhoA, double rhoB, PointSecondDerivativeMatrix& matrix);

/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \param matrix Filled with the upper triangle over rhoA..sigmaBb.
/// \ingroup excgrid-kernels
void Becke88ExchangeSecondDerivatives(double rhoA, double rhoB, double sigmaAa, double sigmaAb,
                                      double sigmaBb, PointSecondDerivativeMatrix& matrix);

/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \param matrix Filled with the upper triangle over rhoA..sigmaBb.
/// \ingroup excgrid-kernels
void PbeExchangeSecondDerivatives(double rhoA, double rhoB, double sigmaAa, double sigmaAb,
                                  double sigmaBb, PointSecondDerivativeMatrix& matrix);

/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \param matrix Filled with the upper triangle over rhoA..sigmaBb.
/// \ingroup excgrid-kernels
void RevPbeExchangeSecondDerivatives(double rhoA, double rhoB, double sigmaAa, double sigmaAb,
                                     double sigmaBb, PointSecondDerivativeMatrix& matrix);

/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \param matrix Filled with the upper triangle over rhoA..sigmaBb.
/// \ingroup excgrid-kernels
void RpbeExchangeSecondDerivatives(double rhoA, double rhoB, double sigmaAa, double sigmaAb,
                                   double sigmaBb, PointSecondDerivativeMatrix& matrix);

/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \param matrix Filled with the upper triangle over rhoA..sigmaBb.
/// \ingroup excgrid-kernels
void MPw91ExchangeSecondDerivatives(double rhoA, double rhoB, double sigmaAa, double sigmaAb,
                                    double sigmaBb, PointSecondDerivativeMatrix& matrix);

/// \}
/// \ingroup excgrid-kernels

} // namespace excgrid
