#pragma once

#include "excgrid/kernel.hpp"

namespace excgrid {

/// \defgroup excgrid-kernels The shipped kernel functions
///
/// Every LDA/GGA functional below is generated by the Yacas codegen
/// pipeline (xc_defs/*.ey -> generated/*.cpp, committed; see
/// tools/regenerate.py and the maintainer guide).  The generated
/// definitions live in excgrid/generated/ and are ordinary library
/// sources - this header is the hand-written declaration surface, kept
/// in sync by the add-a-functional procedure (docs/maintainer-guide.md).
/// Order-1 kernels only - the energy density and the first derivatives,
/// because Vxc assembly consumes nothing above that tier; second/third
/// derivative tiers are a documented generator extension for the
/// analytic-gradient track.
/// \{

/// Slater (Dirac) LDA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue SlaterExchange(double rhoA, double rhoB);

/// VWN5 LDA correlation (the interpolation-V parametrization).
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Vwn5Correlation(double rhoA, double rhoB);

/// VWN3 LDA correlation (the RPA-parameter parametrization) - distinct
/// from VWN5, never conflated.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Vwn3Correlation(double rhoA, double rhoB);

/// PW92 LDA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \returns The energy density and its spin-density derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Pw92Correlation(double rhoA, double rhoB);

/// Becke 1988 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Becke88Exchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Wang 1991 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Pw91Exchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Burke-Ernzerhof 1996 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue PbeExchange(double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// revPBE GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue RevPbeExchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// RPBE (Hammer-Hansen-Norskov 1999) GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue RpbeExchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// mPW91 GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue MPw91Exchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// PBEsol GGA exchange.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue PbeSolExchange(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Lee-Yang-Parr 1988 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue LypCorrelation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Burke-Ernzerhof 1996 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue PbeCorrelation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew-Wang 1991 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue Pw91Correlation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

/// Perdew 1986 GGA correlation.
/// \param rhoA The alpha-spin density.
/// \param rhoB The beta-spin density.
/// \param sigmaAa grad(rhoA) . grad(rhoA).
/// \param sigmaAb grad(rhoA) . grad(rhoB).
/// \param sigmaBb grad(rhoB) . grad(rhoB).
/// \returns The energy density and its first derivatives.
/// \ingroup excgrid-kernels
XcKernelValue P86Correlation(
    double rhoA, double rhoB, double sigmaAa, double sigmaAb, double sigmaBb);

} // namespace excgrid
