#!/usr/bin/env python3
"""Transcribes the DFT-D3 reference data into src/d3_tables.inc.

The committed data files under tools/data/ hold the published DFT-D3
parameter data (Grimme et al., J. Chem. Phys. 132 (2010) 154104), as
distributed numerically in the classic dftd3 program (dftd3.f / pars.f,
the loriab/dftd3 mirror); numeric parameter data only - the excgrid
implementation is fresh code.  The .inc this script writes is committed;
this is a one-time transcription step (run again only when the source
data changes), NOT a per-build codegen step.

Usage:  python tools/gen_d3_tables.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "tools" / "data"
OUT = ROOT / "src" / "d3_tables.inc"

MAX_ELEM = 94
MAX_REF = 7

# --- the C6 reference data: 5-tuples (c6, zA', zB', cnA, cnB) where the
#     primed Z slots carry the CN-reference index in the hundreds digit
#     (z' = z + 100*i means element z, reference index i+1) - the classic
#     dftd3 "limit" encoding.
def read_c6_refs():
    refs = []
    for line in (DATA / "d3_c6_ref.txt").read_text().splitlines():
        if not line.strip():
            continue
        values = [float(token.replace("D", "E")) for token in line.split()]
        assert len(values) == 5, line
        c6, za, zb, cna, cnb = values
        iza, ia = int(za) % 100, int(za) // 100
        izb, ib = int(zb) % 100, int(zb) // 100
        assert 1 <= iza <= MAX_ELEM and 1 <= izb <= MAX_ELEM, line
        refs.append((iza, ib, ia, ib, c6, cna, cnb))
    return refs


def build_tables(refs):
    ref_count = [0] * (MAX_ELEM + 1)
    ref_cn = [[-1.0] * MAX_REF for _ in range(MAX_ELEM + 1)]
    for iza, izb, ia, ib, c6, cna, cnb in refs:
        if cna >= 0.0:
            ref_cn[iza][ia] = cna
        if cnb >= 0.0:
            ref_cn[izb][ib] = cnb
        ref_count[iza] = max(ref_count[iza], ia + 1)
        ref_count[izb] = max(ref_count[izb], ib + 1)

    values = []
    offsets = [[0] * (MAX_ELEM + 1) for _ in range(MAX_ELEM + 1)]
    for iza in range(1, MAX_ELEM + 1):
        for izb in range(1, MAX_ELEM + 1):
            offsets[iza][izb] = len(values)
            pair = [(ia, ib, c6) for (a, b, ia, ib, c6, _, _) in refs
                    if a == iza and b == izb]
            pair.sort()
            for ia, ib, c6 in pair:
                values.append(c6)
    return ref_count, ref_cn, values, offsets


def emit():
    ref_count, ref_cn, values, offsets = build_tables(read_c6_refs())

    def flat(seq, per_line=8):
        out = []
        for i in range(0, len(seq), per_line):
            out.append("    " + ", ".join(repr(v) for v in seq[i:i + per_line]) + ",")
        return "\n".join(out)

    # The r0 pair table (upper-triangle order, Angstrom -> Bohr at fill).
    r0 = [float(v) for v in (DATA / "d3_r0ab.txt").read_text().split()]
    assert len(r0) == MAX_ELEM * (MAX_ELEM + 1) // 2
    r2r4 = [float(v) for v in (DATA / "d3_r2r4.txt").read_text().split()]
    assert len(r2r4) == MAX_ELEM
    rcov = [float(v) for v in (DATA / "d3_rcov.txt").read_text().split()]
    assert len(rcov) == MAX_ELEM

    bohr = 0.529177210903  # 2018 CODATA Bohr radius in Angstrom.
    header = """// Generated by tools/gen_d3_tables.py from the committed DFT-D3
// reference data (tools/data/); do not edit by hand.  Numeric parameter
// data from Grimme et al., J. Chem. Phys. 132 (2010) 154104, as
// distributed in the classic dftd3 program.
//
// Self-sufficient: clang-format's include sort may place this file
// ahead of the consumer's headers, so it carries its own includes.

#include <array>
#include <cstddef>

namespace excgrid::d3tables {
"""
    out = header
    out += "constexpr std::size_t kMaxElement = %d;\n" % MAX_ELEM
    out += "constexpr std::size_t kMaxRef = %d;\n" % MAX_REF
    out += "// Number of CN reference states per element.\n"
    out += "constexpr std::array<int, kMaxElement + 1> kRefCount = {\n"
    out += flat([0] + ref_count[1:]) + "\n};\n"
    # Flat 1-D with index math (kRefCnFlat[z * kMaxRef + i]): MSVC's
    # constexpr evaluator rejects nested std::array aggregates (C2131) -
    # the same lesson the Lebedev tables in this repo record.
    out += "// The CN reference values per element, FLAT: element z's row lives at\n"
    out += "// [z * kMaxRef, z * kMaxRef + kMaxRef), -1 unused.\n"
    out += "constexpr std::array<double, (kMaxElement + 1) * %d> kRefCnFlat = {\n" % MAX_REF
    out += flat([-1.0] * MAX_REF +
                [value for z in range(1, MAX_ELEM + 1) for value in ref_cn[z]]) + "\n};\n"
    out += "// The per-pair C6 reference values, sparse: pair (a, b) occupies\n"
    out += "// [kC6Offset[a][b], kC6Offset[a][b] + kRefCount[a] * kRefCount[b]),\n"
    out += "// CN-a-major order.\n"
    out += "constexpr std::array<double, %d> kC6 = {\n" % len(values)
    out += flat(values) + "\n};\n"
    out += "// Pair offsets into kC6, FLAT row-major over elements 1..kMaxElement\n"
    out += "// (kC6OffsetFlat[a * (kMaxElement + 1) + b]).\n"
    out += "constexpr std::array<int, (kMaxElement + 1) * (kMaxElement + 1)> kC6OffsetFlat = {\n"
    out += flat([0] * (MAX_ELEM + 1) +
                [v for z in range(1, MAX_ELEM + 1) for v in [0] + offsets[z][1:]]) + "\n};\n"
    out += "// The pair cut-off radii r0 (Angstrom in this table; converted\n"
    out += "// to Bohr at load), upper-triangle order.\n"
    out += "constexpr std::array<double, %d> kR0Angstrom = {\n" % len(r0)
    out += flat(r0) + "\n};\n"
    out += "// sqrt(<r^4>/<r^2>) per element, the pre-scaled dftd3 convention.\n"
    out += "constexpr std::array<double, kMaxElement + 1> kR2R4 = {\n"
    out += flat([0.0] + r2r4) + "\n};\n"
    out += "// Covalent radii (Pyykko-Atsumi, k2-scaled), already in Bohr.\n"
    out += "constexpr std::array<double, kMaxElement + 1> kRcov = {\n"
    out += flat([0.0] + rcov) + "\n};\n"
    out += "// The Angstrom-to-Bohr conversion the data was transcribed with.\n"
    out += "constexpr double kBohrPerAngstrom = %.12f;\n" % bohr
    out += "\n} // namespace excgrid::d3tables\n"
    OUT.write_text(out, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(values)} C6 values)")


if __name__ == "__main__":
    emit()
