#!/usr/bin/env python3
"""Transcribes the D4 charge-scaling hardnesses into src/d4_hardness_tables.inc.

Equation 2 of the DFT-D4 model (Caldeweyher, Ehlert, Hansen, Neugebauer,
Spicher, Bannwarth, Grimme, J. Chem. Phys. 150 (2019) 154122) scales the
atomic reference polarizabilities by a function whose element-specific
parameter is the chemical hardness gamma(A).  The paper cites that hardness
to the global atomic hardnesses of Ghosh and Islam (Int. J. Quantum Chem.
110 (2010) 1206-1213, its ref 42) and does not tabulate it; the values live
in the committed data file tools/data/d4_hardness.txt, whose own header
records where they were extracted from and under what terms.

The .inc this script writes is committed; this is a one-time transcription
step (run again only when the source data changes), NOT a per-build codegen
step.

Usage:  python tools/gen_d4_hardness.py            # writes src/d4_hardness_tables.inc
        python tools/gen_d4_hardness.py --check    # verifies the committed file
"""

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "tools" / "data" / "d4_hardness.txt"
OUT = ROOT / "src" / "d4_hardness_tables.inc"

MAX_ELEMENT = 86


def read_rows():
    """The 86 (Z, hardness) rows, in order, comments skipped."""
    rows = []
    for line in DATA.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split()
        assert len(fields) == 2, line
        z = int(fields[0])
        assert z == len(rows) + 1, "rows must run Z = 1..%d in order" % MAX_ELEMENT
        rows.append(float(fields[1]))
    assert len(rows) == MAX_ELEMENT, "%d rows, expected %d" % (len(rows), MAX_ELEMENT)
    return rows


def emit(rows):
    out = []
    add = out.append
    add("// Generated by tools/gen_d4_hardness.py from")
    add("// tools/data/d4_hardness.txt; do not edit by hand.  The")
    add("// element-specific chemical hardnesses that the DFT-D4 charge-scaling")
    add("// function of Caldeweyher, Ehlert, Hansen, Neugebauer, Spicher,")
    add("// Bannwarth, Grimme, J. Chem. Phys. 150 (2019) 154122, equation 2,")
    add("// consumes.")
    add("//")
    add("// Self-sufficient: clang-format's include sort may place this file ahead")
    add("// of the consumer's headers, so it carries its own includes.")
    add("")
    add("#include <cstddef>")
    add("")
    add("namespace excgrid::d4tables {")
    add("")
    add("// The number of tabulated elements (Z = 1..86).")
    add("constexpr std::size_t kHardnessElements = %d;" % len(rows))
    add("")
    add("// Indexed by atomic number: entry k carries element k + 1.  The")
    add("// values are Hartree.")
    add("constexpr double kHardnessTable[] = {")
    for z, hardness in enumerate(rows, start=1):
        add("    %.8f, // %d" % (hardness, z))
    add("};")
    add("")
    add("} // namespace excgrid::d4tables")
    add("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed file instead of writing it")
    args = parser.parse_args()

    rendered = emit(read_rows())

    if args.check:
        committed = OUT.read_text(encoding="utf-8")
        if committed != rendered:
            sys.exit("d4_hardness_tables.inc is stale; re-run without --check")
        print("d4_hardness_tables.inc is current")
        return

    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
