#!/usr/bin/env python3
"""Generate src/d4_tables.inc from the published D4 reference-state data.

The reference states of the DFT-D4 model - Caldeweyher, Ehlert, Hansen,
Neugebauer, Spicher, Bannwarth, Grimme, J. Chem. Phys. 150 (2019) 154122 -
are the atom-in-molecule states that the model's C6 step interpolates over.  The
paper defines them (its equations 5, 7 and 8) but does not tabulate them; the
numeric values are carried by the reference implementation's generated data.

The 23-point frequency grid its equation 9 integrates over is taken from the
same distribution's own model data, again values only.

This script transcribes NUMBERS ONLY, as the project's D3 parameter data was
transcribed: the reference charge, the reference coordination number in both the
D4 and the D3 definition, the scale the published data carries per state, the
23 isotropically averaged dynamic polarizabilities alpha(iw) of each state, and
the frequencies those polarizabilities stand on.  No statement, comment,
structure or expression of the source is reproduced; the output is this
project's own table in this project's own format, and it names each number for
where it sits rather than for the role it is believed to play.

Usage:  python tools/gen_d4_tables.py            # writes src/d4_tables.inc
        python tools/gen_d4_tables.py --check    # verifies the committed file
"""

import argparse
import pathlib
import re
import sys
import urllib.request

SOURCE = "https://raw.githubusercontent.com/dftd4/dftd4/main/src/dftd4/reference.inc"
MODEL_SOURCE = "https://raw.githubusercontent.com/dftd4/dftd4/main/src/dftd4/model/utils.f90"
OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "d4_tables.inc"

# The secondary reference systems, in the order the source carries them, with the
# formula each one is named by and the state index of its reference state in the
# source's own global numbering.  Which element a state is a reference for is NOT
# recorded here: a system can serve more than one element (CO carries a carbon and
# an oxygen reference), so that assignment belongs to the model code, not the table.
SYSTEMS = [
    ("null", 1),
    ("H2", 2),
    ("C6H6", 6),
    ("NH3", 7),
    ("CO", 8),
    ("O2", 9),
    ("N2", 10),
    ("F2", 11),
    ("Cl2", 17),
]

N_FREQUENCIES = 23


def fetch(url):
    with urllib.request.urlopen(url, timeout=120) as response:
        return response.read().decode("utf-8", errors="replace")


def parse(text):
    def scalars(name):
        pattern = r"data\s+%s\s*\((\d+)\)\s*/\s*([-\d.E+]+)_wp" % name
        return {int(m.group(1)): float(m.group(2)) for m in re.finditer(pattern, text)}

    charge = scalars("secq")
    scale = scalars("sscale")
    cn = scalars("seccn")
    cn_d3 = scalars("seccnD3")

    alpha = {}
    pattern = r"data\s+secaiw\s*\(:,(\d+)\)\s*/(.*?)/"
    for m in re.finditer(pattern, text, re.S):
        alpha[int(m.group(1))] = [float(v) for v in re.findall(r"([-\d.]+)_wp", m.group(2))]

    states = []
    for name, index in SYSTEMS:
        values = alpha[index]
        if len(values) != N_FREQUENCIES:
            raise SystemExit("state %d: %d frequencies, expected %d"
                             % (index, len(values), N_FREQUENCIES))
        states.append({
            "system": name,
            "charge": charge[index],
            "scale": scale[index],
            "cn": cn[index],
            "cnD3": cn_d3[index],
            "alpha": values,
        })
    return states


def parse_frequencies(text):
    """The model's 23 Casimir-Polder frequencies, in Hartree."""
    match = re.search(r"freq\s*\(\s*(\d+)\s*\)\s*=\s*\[(.*?)\]", text, re.S)
    if match is None:
        raise SystemExit("no frequency grid found in the model data")
    if int(match.group(1)) != N_FREQUENCIES:
        raise SystemExit("frequency grid declares %s points, expected %d"
                         % (match.group(1), N_FREQUENCIES))
    values = [float(v) for v in re.findall(r"([-\d.]+)", match.group(2))]
    if len(values) != N_FREQUENCIES:
        raise SystemExit("frequency grid has %d points, expected %d"
                         % (len(values), N_FREQUENCIES))
    if any(b <= a for a, b in zip(values, values[1:])):
        raise SystemExit("frequency grid is not strictly increasing")
    return values


def emit(states, frequencies):
    out = []
    add = out.append
    add("// Generated by tools/gen_d4_tables.py from the published DFT-D4")
    add("// reference-state data; do not edit by hand.  Numeric values only, from")
    add("// Caldeweyher, Ehlert, Hansen, Neugebauer, Spicher, Bannwarth, Grimme,")
    add("// J. Chem. Phys. 150 (2019) 154122 (the model), as carried by the")
    add("// reference implementation's generated data (see THIRD_PARTY_NOTICES.md).")
    add("//")
    add("// Self-sufficient: clang-format's include sort may place this file ahead")
    add("// of the consumer's headers, so it carries its own includes.")
    add("")
    add("#include <array>")
    add("#include <cstddef>")
    add("")
    add("namespace excgrid::d4tables {")
    add("")
    add("// The number of reference states and of Casimir-Polder frequencies.")
    add("constexpr std::size_t kReferenceStates = %d;" % len(states))
    add("constexpr std::size_t kFrequencies = %d;" % N_FREQUENCIES)
    add("")
    add("// One reference state: the formula of the reference system it is taken")
    add("// from, its reference charge, its reference coordination number in the")
    add("// D4 and the D3 definition, and the scale the published data carries for")
    add("// it.  The scale's role in the model is NOT asserted here: these are the")
    add("// published numbers, named for where they sit, not for what they do.")
    add("struct ReferenceState {")
    add("    const char* system;")
    add("    double charge;")
    add("    double coordinationNumber;")
    add("    double coordinationNumberD3;")
    add("    double scale;")
    add("};")
    add("")
    add("constexpr ReferenceState kReferenceStateTable[] = {")
    for s in states:
        add('    {"%s", %.7f, %.7f, %.7f, %.7f},'
            % (s["system"], s["charge"], s["cn"], s["cnD3"], s["scale"]))
    add("};")
    add("")
    add("// The 23 isotropically averaged dynamic polarizabilities alpha(iw) of")
    add("// each reference state, FLAT: state k's row starts at k * kFrequencies.")
    add("// Column j stands on frequency j of kFrequencyGrid.")
    add("constexpr std::array<double, kReferenceStates * kFrequencies> kReferenceAlpha = {")
    for s in states:
        row = ", ".join("%.7f" % v for v in s["alpha"])
        add("    // %s" % s["system"])
        add("    %s," % row)
    add("};")
    add("")
    add("// The frequencies, in Hartree, the polarizabilities above are given")
    add("// on: strictly increasing, and the abscissae the model's equation 9")
    add("// integrates over by the trapezium rule.")
    add("constexpr std::array<double, kFrequencies> kFrequencyGrid = {")
    add("    %s," % ", ".join("%.6f" % w for w in frequencies))
    add("};")
    add("")
    add("} // namespace excgrid::d4tables")
    add("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed file instead of writing it")
    parser.add_argument("--source", default=SOURCE,
                        help="override the source URL (for offline re-runs)")
    parser.add_argument("--model-source", default=MODEL_SOURCE,
                        help="override the model-data URL (for offline re-runs)")
    args = parser.parse_args()

    text = fetch(args.source)
    model = fetch(args.model_source)
    rendered = emit(parse(text), parse_frequencies(model))

    if args.check:
        committed = OUTPUT.read_text(encoding="utf-8")
        if committed != rendered:
            sys.exit("d4_tables.inc is stale; re-run without --check")
        print("d4_tables.inc is current")
        return

    # newline="" style: always LF, so the committed file is byte-identical
    # on a fresh checkout and --check means what it says.
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print("wrote %s" % OUTPUT)


if __name__ == "__main__":
    main()
