#!/usr/bin/env python3
"""Transcribes Table A1 of the DFT-D4 paper into src/d4_eeq_tables.inc.

The committed data file tools/data/d4_eeq_a1.txt holds the published EEQ
element parameters of the DFT-D4 model (Caldeweyher, Ehlert, Hansen,
Neugebauer, Spicher, Bannwarth, Grimme, J. Chem. Phys. 150 (2019) 154122),
as the paper's Supplementary Material Table A1 tabulates them for
Z = 1..86: the atomic electronegativity EN, the element-dependent atomic
hardness J, the element-specific scaling parameter kappa, and the atomic
radius a.  The data file's own header records how it was extracted.

The .inc this script writes is committed; this is a one-time transcription
step (run again only when the source table changes), NOT a per-build codegen
step.

Usage:  python tools/gen_d4_eeq.py            # writes src/d4_eeq_tables.inc
        python tools/gen_d4_eeq.py --check    # verifies the committed file
"""

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "tools" / "data" / "d4_eeq_a1.txt"
OUT = ROOT / "src" / "d4_eeq_tables.inc"

MAX_ELEMENT = 86


def read_rows():
    """The 86 (Z, EN, J, kappa, a) rows, in order, comments skipped."""
    rows = []
    for line in DATA.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split()
        assert len(fields) == 5, line
        z = int(fields[0])
        assert z == len(rows) + 1, "rows must run Z = 1..%d in order" % MAX_ELEMENT
        rows.append(tuple(float(v) for v in fields[1:]))
    assert len(rows) == MAX_ELEMENT, "%d rows, expected %d" % (len(rows), MAX_ELEMENT)
    return rows


def emit(rows):
    out = []
    add = out.append
    add("// Generated by tools/gen_d4_eeq.py from tools/data/d4_eeq_a1.txt;")
    add("// do not edit by hand.  The published EEQ element parameters of the")
    add("// DFT-D4 model (Caldeweyher, Ehlert, Hansen, Neugebauer, Spicher,")
    add("// Bannwarth, Grimme, J. Chem. Phys. 150 (2019) 154122), as the paper's")
    add("// Supplementary Material Table A1 tabulates them (pages S4-S6).")
    add("//")
    add("// Self-sufficient: clang-format's include sort may place this file ahead")
    add("// of the consumer's headers, so it carries its own includes.")
    add("")
    add("#include <cstddef>")
    add("")
    add("namespace excgrid::d4tables {")
    add("")
    add("// The number of tabulated elements (Z = 1..86).")
    add("constexpr std::size_t kEeqElements = %d;" % len(rows))
    add("")
    add("// One element's published EEQ parameters, in atomic units: the atomic")
    add("// electronegativity EN (Hartree), the element-dependent atomic hardness")
    add("// J (Hartree), the element-specific scaling parameter kappa")
    add("// (dimensionless), and the atomic radius a (Bohr).")
    add("struct EeqElement {")
    add("    double electronegativity;")
    add("    double hardness;")
    add("    double coordinationScale;")
    add("    double radius;")
    add("};")
    add("")
    add("// Indexed by atomic number: entry k carries element k + 1.")
    add("constexpr EeqElement kEeqElementTable[] = {")
    for z, (en, hardness, kappa, radius) in enumerate(rows, start=1):
        add("    {%.8f, %.8f, %.8f, %.8f}, // %d" % (en, hardness, kappa, radius, z))
    add("};")
    add("")
    add("} // namespace excgrid::d4tables")
    add("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed file instead of writing it")
    args = parser.parse_args()

    rendered = emit(read_rows())

    if args.check:
        committed = OUT.read_text(encoding="utf-8")
        if committed != rendered:
            sys.exit("d4_eeq_tables.inc is stale; re-run without --check")
        print("d4_eeq_tables.inc is current")
        return

    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
