#!/usr/bin/env python3
"""Transcribes the D4 coordination-number element data into src/d4_cn_tables.inc.

Equation 6 of the DFT-D4 model (Caldeweyher, Ehlert, Hansen, Neugebauer,
Spicher, Bannwarth, Grimme, J. Chem. Phys. 150 (2019) 154122) consumes two
element tables the paper cites but does not carry: the covalent radii of
ref 48 (Pyykko and Atsumi) and the Pauling electronegativities of ref 47.
Both live in the committed data file tools/data/d4_cn_element.txt, whose
own header records where they were extracted from and under what terms.

The data file carries the radii as published, in Angstrom; the .inc carries
them both as published and multiplied by 4/3 (the counting convention of the
earlier D3 method), which is the set the counting function scales by.

The .inc this script writes is committed; this is a one-time transcription
step (run again only when the source data changes), NOT a per-build codegen
step.

Usage:  python tools/gen_d4_cn_tables.py            # writes src/d4_cn_tables.inc
        python tools/gen_d4_cn_tables.py --check    # verifies the committed file
"""

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "tools" / "data" / "d4_cn_element.txt"
OUT = ROOT / "src" / "d4_cn_tables.inc"

MAX_ELEMENT = 86
ANGSTROM_PER_BOHR = 0.529177210903  # 2018 CODATA, the same constant the D3 tables use.
D3_RADIUS_SCALE = 4.0 / 3.0  # The counting convention of the earlier D3 method.


def read_rows():
    """The 86 (Z, radius, EN) rows, in order, comments skipped."""
    rows = []
    for line in DATA.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split()
        assert len(fields) == 3, line
        z = int(fields[0])
        assert z == len(rows) + 1, "rows must run Z = 1..%d in order" % MAX_ELEMENT
        rows.append(tuple(float(v) for v in fields[1:]))
    assert len(rows) == MAX_ELEMENT, "%d rows, expected %d" % (len(rows), MAX_ELEMENT)
    return rows


def emit(rows):
    out = []
    add = out.append
    add("// Generated by tools/gen_d4_cn_tables.py from")
    add("// tools/data/d4_cn_element.txt; do not edit by hand.  The covalent")
    add("// radii (Pyykko and Atsumi, Chem. Eur. J. 15 (2009) 186-197) and the")
    add("// Pauling electronegativities that the DFT-D4 coordination number of")
    add("// Caldeweyher, Ehlert, Hansen, Neugebauer, Spicher, Bannwarth,")
    add("// Grimme, J. Chem. Phys. 150 (2019) 154122, equation 6, consumes.")
    add("//")
    add("// Self-sufficient: clang-format's include sort may place this file ahead")
    add("// of the consumer's headers, so it carries its own includes.")
    add("")
    add("#include <cstddef>")
    add("")
    add("namespace excgrid::d4tables {")
    add("")
    add("// The number of tabulated elements (Z = 1..86).")
    add("constexpr std::size_t kCnElements = %d;" % len(rows))
    add("")
    add("// One element's coordination-number data.  The radii are in Bohr;")
    add("// the electronegativity is the dimensionless Pauling value.  Both")
    add("// radius sets are carried: the published one, and the 4/3-scaled one")
    add("// the counting function scales by, which is the convention of the")
    add("// earlier D3 method.")
    add("struct CnElement {")
    add("    double covalentRadiusPublished;")
    add("    double covalentRadiusD3;")
    add("    double paulingElectronegativity;")
    add("};")
    add("")
    add("// Indexed by atomic number: entry k carries element k + 1.")
    add("constexpr CnElement kCnElementTable[] = {")
    for z, (radius, en) in enumerate(rows, start=1):
        add("    {%.12f, %.12f, %.2f}, // %d"
            % (radius / ANGSTROM_PER_BOHR, radius * D3_RADIUS_SCALE / ANGSTROM_PER_BOHR, en, z))
    add("};")
    add("")
    add("} // namespace excgrid::d4tables")
    add("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed file instead of writing it")
    args = parser.parse_args()

    rendered = emit(read_rows())

    if args.check:
        committed = OUT.read_text(encoding="utf-8")
        if committed != rendered:
            sys.exit("d4_cn_tables.inc is stale; re-run without --check")
        print("d4_cn_tables.inc is current")
        return

    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
